[keys]
move_left = "Left"
move_right = "Right"
move_down = "Down"
rotate_left = "a"
rotate_right = "d"
rotate_180 = "w"
hard_drop = "Space"
hold = "c"
pause = "Escape"

[display]
block_style = "Thick"
